spring.application.name=FDS_AML

# spring.datasource.url=jdbc:mysql://localhost:3306/capstone
# spring.datasource.username=root
# spring.datasource.password=2828

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

ai.qwen.url=https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions
ai.qwen.api-key=sk-92c096e5290248d091a3769277687daf